Resources:
  LevelHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LevelHistory
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "S"
        - AttributeName: "level"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "gameId"
          KeyType: "HASH"
        - AttributeName: "level"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"