Resources:
  ShipInformationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ShipInformation
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "S"
        - AttributeName: "playerCoordinates"
          AttributeType: "S"
        - AttributeName: "alienCoordinates"
          AttributeType: "S"
        - AttributeName: "playerHealth"
          AttributeType: "N"
        - AttributeName: "alienHealth"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "gameId"
          keyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"