Resources:
  ShipInformationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ShipInformation
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "gameId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"